# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-06 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20181203_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shiping_total',
            new_name='shipping_total',
        ),
    ]
